theme: minima
title: Tradespotting Deep Learning
author: Drnochill
email: no need for my email, punk
description: > # this means to ignore newlines until "baseurl:"
 Here we learn how not to buy the top and sell the bottom

# social links
twitter_username: _Jamie_Curran
github_username:  Drnochill

show_excerpts: false # set to false to remove excerpts on the homepage
